Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -38,10 +38,13 @@ jobs:
 
     - name: Commit & Push Report
       run: |
-        git config --global user.name "UnnatiBot"
-        git config --global user.email "unnatibot@example.com"
         mkdir -p reports
-        cp report.md reports/report_$(date +'%Y-%m-%d').md
-        git add reports/
-        git commit -m "🗒️ Add Threat Report - $(date +'%Y-%m-%d')" || echo "No changes to commit"
-        git push
+        if [ -f report.md ]; then
+          cp report.md reports/report_$(date +'%Y-%m-%d').md
+          git config user.name "UnnatiBot"
+          git config user.email "unnati@example.com"
+          git add reports/
+          git commit -m "Add daily threat report - $(date +'%Y-%m-%d')" || echo "No changes to commit"
+          git push
+        else
+            echo "⚠️ report.md not found, skipping commit & push."
